const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
let motionPaused=reduced.matches, currentScene='exterior';
$('#year').textContent=new Date().getFullYear();
function syncMotion(){document.body.classList.toggle('motion-paused',motionPaused);$('#pause-motion').textContent=motionPaused?'Enable motion':'Pause motion';$('#pause-motion').setAttribute('aria-pressed',motionPaused);window.dispatchEvent(new CustomEvent('motionchange',{detail:motionPaused}));}
$('#pause-motion').onclick=()=>{motionPaused=!motionPaused;syncMotion()};reduced.addEventListener('change',()=>{motionPaused=reduced.matches;syncMotion()});syncMotion();
$$('dialog').forEach(d=>{d.querySelector('.close').onclick=()=>d.close();d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}})});
$$('[data-brief]').forEach(b=>b.onclick=()=>$('#brief-dialog').showModal());
const projects={exterior:{title:'The Quiet Residence',type:'EXTERIOR / CONCEPT DIRECTION',text:'A study in clean volumes, deep overhangs and the relationship between a home and its landscape. Glass opens the living spaces to the outside; a restrained material palette gives the architecture room to speak.',image:'assets/exterior.jpg'},interior:{title:'A Softer Kind of Living',type:'INTERIOR / CONCEPT DIRECTION',text:'An exploration of tactile materials, sculptural furniture and comfortable proportions. Natural light draws out the texture, while a quiet palette lets everyday life take centre stage.',image:'assets/interior.jpg'}};
$$('[data-project]').forEach(b=>b.onclick=()=>{currentScene=b.dataset.project;const p=projects[currentScene];$('#detail-title').textContent=p.title;$('#detail-type').textContent=p.type;$('#detail-text').textContent=p.text;$('#detail-image').src=p.image;$('#detail-image').alt=p.title;$('#project-dialog').showModal()});
$('#try-model').onclick=()=>{$('#project-dialog').close();document.querySelector(`[data-scene="${currentScene}"]`).click();$('#playground').scrollIntoView({behavior:motionPaused?'instant':'smooth'})};
$$('[data-filter]').forEach(b=>b.onclick=()=>{$$('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',x===b));$$('[data-project]').forEach(x=>x.hidden=b.dataset.filter!=='all'&&x.dataset.project!==b.dataset.filter);$('.project-grid').classList.toggle('filtered',b.dataset.filter!=='all')});
$('#brief-form').onsubmit=e=>{e.preventDefault();const details=$('#brief-space').value.trim();if(!details){$('#brief-space').setCustomValidity('Tell us a little about your space.');$('#brief-space').reportValidity();return}const text=`FIFFY STUDIO — PROJECT BRIEF\n\nService: ${$('#brief-service').value}\nTimeline: ${$('#brief-time').value}\n\nYour space\n${details}\n\nCreated with the Fiffy Studio concept website. This brief has not been submitted.\n`;const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='fiffy-project-brief.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('#brief-status').textContent='Your brief is ready. Save the downloaded file to share it.'};$('#brief-space').oninput=()=>$('#brief-space').setCustomValidity('');
$('#image-credits').innerHTML='<p>Exterior visual: <a href="https://unsplash.com/photos/a-rendering-of-a-modern-house-with-a-pool-IPkPnaazXSY" target="_blank" rel="noopener">Salman Saqib / SD Studio, Unsplash</a>.</p><p>Interior visual: <a href="https://unsplash.com/photos/modern-living-room-with-sectional-sofa-and-artwork-ugIfsN9l_q4" target="_blank" rel="noopener">Aalo Lens, Unsplash</a>.</p>';$('#credits').onclick=()=>$('#credits-dialog').showModal();
if('IntersectionObserver'in window){const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){if(!motionPaused)e.target.classList.add('reveal');io.unobserve(e.target)}}),{threshold:.12});$$('.intro>div,.section-head,.project,.process-grid article').forEach(x=>io.observe(x))}
async function init3D(){
 const THREE=await import('three');const {OrbitControls}=await import('./assets/OrbitControls.js');
 const host=$('#scene');const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;host.appendChild(renderer.domElement);
 const scene=new THREE.Scene();scene.background=new THREE.Color('#c9cec0');const camera=new THREE.PerspectiveCamera(38,1,.1,100);camera.position.set(11,8,13);
 const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,1,0);controls.enableDamping=true;controls.enablePan=false;controls.minDistance=7;controls.maxDistance=25;controls.maxPolarAngle=Math.PI/2.08;controls.minPolarAngle=.25;controls.autoRotate=!motionPaused;controls.autoRotateSpeed=.55;controls.enableZoom=true;
 const hemi=new THREE.HemisphereLight('#faf9e8','#647657',2.6);scene.add(hemi);const sun=new THREE.DirectionalLight('#fff4db',4);sun.position.set(-5,10,7);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-12,right:12,top:12,bottom:-12,near:.1,far:50});sun.shadow.bias=-.001;scene.add(sun);
 const mat=(color,extra={})=>new THREE.MeshStandardMaterial({color,roughness:.8,...extra});const finish=mat('#cfccbb'), white=mat('#e9e6d9'),wood=mat('#88694b'),black=mat('#292e29'),glass=mat('#5e8e88',{metalness:.6,roughness:.2}),green=mat('#667850'),water=mat('#648f88',{metalness:.5,roughness:.15}),sofa=mat('#dbd3bd'),rug=mat('#958d73');
 const model=new THREE.Group();scene.add(model);const exterior=new THREE.Group(),interior=new THREE.Group();model.add(exterior,interior);interior.visible=false;
 function box(parent,w,h,d,x,y,z,m){const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o}
 function cylinder(parent,rt,rb,h,x,y,z,m){const o=new THREE.Mesh(new THREE.CylinderGeometry(rt,rb,h,32),m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o}
 const ground=new THREE.Mesh(new THREE.PlaneGeometry(200,200),mat('#c9cec0'));ground.rotation.x=-Math.PI/2;ground.position.y=-.13;ground.receiveShadow=true;scene.add(ground);
 box(exterior,11,.25,9,0,0,0,white);box(exterior,7.4,.25,4.5,0,.32,-.6,finish);box(exterior,7.1,2.5,.2,0,1.67,-2.65,finish);box(exterior,.23,2.5,4.4,-3.45,1.67,-.5,finish);box(exterior,.23,2.5,4.4,3.45,1.67,-.5,finish);box(exterior,7.8,.3,4.9,0,3,-.55,finish);
 box(exterior,6.6,2.3,.07,0,1.7,1.54,glass);for(let x=-3.3;x<=3.31;x+=1.1)box(exterior,.055,2.4,.15,x,1.67,1.55,black);box(exterior,3.4,2.3,3.1,-1.5,4.28,-.85,finish);box(exterior,3.2,1.8,.08,-1.5,4.25,.73,glass);box(exterior,3.8,.22,3.5,-1.5,5.5,-.85,white);for(let x=-3.1;x<.15;x+=.8)box(exterior,.055,1.8,.14,x,4.25,.77,black);
 box(exterior,3.4,.15,2.8,2.1,.19,3,water);box(exterior,3.75,.1,.18,2.1,.29,1.52,white);box(exterior,.18,.1,3,3.89,.29,3,white);box(exterior,3.75,.1,.18,2.1,.29,4.47,white);box(exterior,.18,.1,3,.29,.29,3,white);
 for(let i=0;i<6;i++)box(exterior,.9,.07,.42,-2,.18,2+i*.45,wood);for(let x=-3.2;x<=3.2;x+=.32)box(exterior,.10,1.2,.12,x,3.48,1.77,wood);box(exterior,7,.08,.12,0,4.05,1.77,black);
 function plant(parent,x,z,s=1){cylinder(parent,.3*s,.23*s,.45*s,x,.25*s,z,white);cylinder(parent,.045*s,.06*s,1.4*s,x,.9*s,z,wood);const crown=new THREE.Mesh(new THREE.IcosahedronGeometry(.65*s,1),green);crown.position.set(x,1.8*s,z);crown.scale.y=1.25;crown.castShadow=true;parent.add(crown)}plant(exterior,-4.5,-2,1.2);plant(exterior,4.5,-2.3,1);plant(exterior,-4,3,.65);
 box(interior,8,.25,6,0,0,0,wood);box(interior,8,3.5,.18,0,1.78,-3,finish);box(interior,.18,3.5,6,-4,1.78,0,finish);box(interior,.06,2.8,3.8,-3.88,1.7,-.55,glass);for(let z=-2.5;z<=1.3;z+=1.25)box(interior,.1,3,.05,-3.82,1.7,z,black);
 box(interior,4.8,.03,3.5,.35,.15,.2,rug);box(interior,4,.5,1.3,.4,.53,-1.6,sofa);box(interior,4,.85,.26,.4,.91,-2.13,sofa);box(interior,.25,.68,1.4,-1.5,.77,-1.57,sofa);box(interior,.25,.68,1.4,2.3,.77,-1.57,sofa);for(let x=-.85;x<=1.7;x+=1.25)box(interior,1.13,.16,1,x,.86,-1.55,white);box(interior,1.1,.48,2,1.65,.54,-.2,sofa);
 cylinder(interior,.95,.95,.12,-.35,.7,.45,wood);cylinder(interior,.35,.48,.5,-.35,.4,.45,black);cylinder(interior,.22,.18,.25,-.2,.9,.45,white);box(interior,1.7,1.8,.08,.5,2.35,-2.86,black);box(interior,1.5,1.6,.09,.5,2.35,-2.8,rug);box(interior,.55,1.35,.1,.2,2.35,-2.73,wood);
 plant(interior,-2.9,1.9,.9);cylinder(interior,.42,.42,.09,2.8,.2,1.7,black);cylinder(interior,.035,.035,2.4,2.8,1.4,1.7,black);cylinder(interior,.3,.65,.55,2.8,2.55,1.7,white);
 let rotating=!motionPaused,visible=true;function rotationLabel(){$('#auto-rotate').setAttribute('aria-pressed',rotating);$('#auto-rotate').textContent=rotating?'Pause rotation':'Auto rotate'}rotationLabel();$('#auto-rotate').onclick=()=>{rotating=!rotating;controls.autoRotate=rotating;rotationLabel()};window.addEventListener('motionchange',e=>{rotating=!e.detail;controls.autoRotate=rotating;rotationLabel()});
 function reset(){camera.position.set(currentScene==='interior'?9:11,currentScene==='interior'?7:8,currentScene==='interior'?11:13);controls.target.set(0,1,0);controls.update()}$('#reset').onclick=reset;
 function rotate(angle){const offset=camera.position.clone().sub(controls.target);offset.applyAxisAngle(new THREE.Vector3(0,1,0),angle);camera.position.copy(controls.target).add(offset);rotating=false;controls.autoRotate=false;rotationLabel();controls.update()}$('#rotate-left').onclick=()=>rotate(-Math.PI/6);$('#rotate-right').onclick=()=>rotate(Math.PI/6);
 controls.addEventListener('start',()=>{rotating=false;controls.autoRotate=false;rotationLabel()});
 $$('[data-scene]').forEach(b=>b.onclick=()=>{currentScene=b.dataset.scene;exterior.visible=currentScene==='exterior';interior.visible=!exterior.visible;$$('[data-scene]').forEach(x=>x.setAttribute('aria-pressed',x===b));$('#model-title').textContent=exterior.visible?'The Courtyard House':'The Living Room';reset()});
 $$('[data-finish]').forEach(b=>b.onclick=()=>{const options={stone:['#cfccbb','Limestone'],clay:['#ad6950','Terracotta'],dark:['#51544d','Graphite']};const choice=options[b.dataset.finish];finish.color.set(choice[0]);$('#finish-name').textContent=choice[1];$$('[data-finish]').forEach(x=>x.setAttribute('aria-pressed',x===b))});
 $$('[data-light]').forEach(b=>b.onclick=()=>{const dusk=b.dataset.light==='dusk';scene.background.set(dusk?'#a39989':'#c9cec0');ground.material.color.copy(scene.background);sun.color.set(dusk?'#ffb974':'#fff4db');sun.position.set(-5,dusk?3:10,7);sun.intensity=dusk?3.7:4;hemi.intensity=dusk?1.3:2.6;$$('[data-light]').forEach(x=>x.setAttribute('aria-pressed',x===b))});
 new ResizeObserver(()=>{const w=host.clientWidth,h=host.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix()}).observe(host);
 new IntersectionObserver(e=>visible=e[0].isIntersecting).observe(host);let previous=0;renderer.setAnimationLoop(t=>{if(!visible||document.hidden)return;const delta=Math.min((t-previous)/1000,.05);previous=t;controls.update(delta);renderer.render(scene,camera)});$('#loading').hidden=true;
}
init3D().catch(()=>{$('#loading').textContent='The interactive model needs WebGL. You can still explore the concept gallery below.';$$('.controls button,.viewer-foot button').forEach(b=>b.disabled=true)});
